import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  // title: "Create Next App",
  title: "Gavin's Shopping List",
  // description: "Generated by create next app",
  description: "My web development 2 assignments",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
